export default {
  SET_LOADING: 'SET_LOADING',
  SET_ALERTS: 'SET_ALERTS',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  CHANGE_TITLE: 'CHANGE_TITLE',
  CHANGE_SUBTEXT: 'CHANGE_SUBTEXT',
};
